const VERIFY_CODE_SENT = 2210;
const USER_CREATED = 2211;
const USER_UPDATED = 2212;
const RESPONSE_SUCCESSFUL = 2213;
const PAYMENTS_WERE_MADE = 2214;
const INVOICE_CREATED = 2215;
const INVOICE_UPDATED = 2216;
const RESPONSE_DELETE = 2240;

const ERROR_PARAM = 5010;

const ERROR_NOT_A_NUMBER = 6011;
const ERROR_INVALID_PHONE_NUMBER = 6012;
const ERROR_SMS_NOT_SEND = 6013;
const ERROR_INVALID_VERIFY_NUMBER = 6014;
const ERROR_TOO_MANY_ATTEMPT = 6015;
const ERROR_TYPE_NOT_MACH = 6016;
const ERROR_TOKEN = 6017;
const ERROR_GENDER = 6018;
const ERROR_FULL_NAME_MUST_STRING = 6019;
const ERROR_WRONG_PARAMETER = 6020;
const ERROR_WRONG_PAYMENT_REASON = 6021;
const ERROR_DUPLICATE = 6022;
const ERROR_NOT_FOUND = 6023;
const ERROR_FORBIDDEN = 6024;
const ERROR_FINANCIALGROUP_IS_ALREADY_USED = 6025;
const ERROR_TRANSACTION_NOT_FOUND = 6026;
const ERROR_IN_CALL_BACK_TRANSACTION_PARAM = 6027;
const ERROR_UNSUCCESSFUL_PAYMENT = 6028;
const ERROR_TARGET_NOT_FOUND = 6029;
const ERROR_INSUFFICIENT_BALANCE = 6030;
const ERROR_DRIVER_IS_NOT_IN_DEBT = 6031;
const ERROR_HAVE_UNVERIFIED_INVOICE = 6032;
const ERROR_INVOICE_STATUS_NOT_SLECTED = 6033;
const ERROR_REASEN_NOT_MATCH = 6034;
const ERROR_INVOICE_STATUS_NOT_MATCH = 6035;
const OLD_TRANSACTION = 6036;
const ERROR_TRANSACTION = 6037;
const ERROR_AMOUNT_ENTERED_IS_LESS_THAN_THE_DEBT = 6038;
const ERROR_SADERAT_TOKEN = 6039;
const ERROR_AMOUNT_ENTERED_IS_LESS_THAN_BALANCE = 6040;
const ERROR_SERVICE_NOT_FOUND = 6041;

const ERROR_TRACKING_CODE_DUPLICATE = 6041;
const ERROR_BANK_iNFORMATION_NOT_FOUND = 6042;
const ERROR_WITHDRAWAL_ID_NOT_FOUND = 6043;
const ERROR_WITHDRAWAL_STATUS_NOT_PENDING = 6044;
const ERROR_ZARINPAL_TOKEN = 6045;
const ERROR_AMOUNT_ENTERED_IS_LESS_THAN_MIN_WITHDRAWAL = 6046;
const ERROR_AMOUNT_ENTERED_IS_MORE_THAN_MAX_WITHDRAWAL = 6047;
const ERROR_FACTOR_NOT_FOUND = 6048;
const ERROR_ONLY_ADMIN = 6049;
const ERROR_DEBT_NOT_FOUND = 6050;
const ERROR_ONLY_COMPANY = 6051;

const USER_BLOCK_FOR_SUBSCRIPTION = 7071;

const ERROR_REDIS = 5097;
const AUTH_FAILED = 5098;
const ERROR_INTERNAL = 5099;

module.exports = {
  ERROR_SERVICE_NOT_FOUND,
  ERROR_ONLY_COMPANY,
  ERROR_DEBT_NOT_FOUND,
  ERROR_ONLY_ADMIN,
  ERROR_FORBIDDEN,
  ERROR_WITHDRAWAL_STATUS_NOT_PENDING,
  ERROR_NOT_FOUND,
  VERIFY_CODE_SENT,
  USER_CREATED,
  ERROR_SADERAT_TOKEN,
  USER_BLOCK_FOR_SUBSCRIPTION,
  ERROR_TRACKING_CODE_DUPLICATE,
  PAYMENTS_WERE_MADE,
  ERROR_REASEN_NOT_MATCH,
  USER_UPDATED,
  ERROR_FACTOR_NOT_FOUND,
  AUTH_FAILED,
  ERROR_INTERNAL,
  ERROR_PARAM,
  ERROR_HAVE_UNVERIFIED_INVOICE,
  ERROR_NOT_A_NUMBER,
  ERROR_INVOICE_STATUS_NOT_SLECTED,
  ERROR_INVALID_PHONE_NUMBER,
  ERROR_WITHDRAWAL_ID_NOT_FOUND,
  ERROR_INSUFFICIENT_BALANCE,
  ERROR_SMS_NOT_SEND,
  ERROR_INVALID_VERIFY_NUMBER,
  ERROR_TOO_MANY_ATTEMPT,
  ERROR_IN_CALL_BACK_TRANSACTION_PARAM,
  ERROR_TOKEN,
  ERROR_TYPE_NOT_MACH,
  ERROR_REDIS,
  ERROR_GENDER,
  ERROR_TARGET_NOT_FOUND,
  ERROR_FULL_NAME_MUST_STRING,
  INVOICE_CREATED,
  ERROR_FINANCIALGROUP_IS_ALREADY_USED,
  ERROR_WRONG_PARAMETER,
  ERROR_WRONG_PAYMENT_REASON,
  ERROR_TRANSACTION_NOT_FOUND,
  RESPONSE_SUCCESSFUL,
  OLD_TRANSACTION,
  ERROR_BANK_iNFORMATION_NOT_FOUND,
  ERROR_TRANSACTION,
  ERROR_INVOICE_STATUS_NOT_MATCH,
  ERROR_UNSUCCESSFUL_PAYMENT,
  RESPONSE_DELETE,
  ERROR_DUPLICATE,
  ERROR_DRIVER_IS_NOT_IN_DEBT,
  ERROR_AMOUNT_ENTERED_IS_LESS_THAN_THE_DEBT,
  ERROR_AMOUNT_ENTERED_IS_LESS_THAN_BALANCE,
  INVOICE_UPDATED,
  ERROR_ZARINPAL_TOKEN,
  ERROR_AMOUNT_ENTERED_IS_LESS_THAN_MIN_WITHDRAWAL,
  ERROR_AMOUNT_ENTERED_IS_MORE_THAN_MAX_WITHDRAWAL,
};
