const ADMIN = "ADMIN";
const DRIVER = "DRIVER";
const COMPANY = "COMPANY";
const PASSENGER = "PASSENGER";
const SUPER_AGENT_SCHOOL = "SUPER_AGENT_SCHOOL";

module.exports = {
  ADMIN,
  DRIVER,
  COMPANY,
  PASSENGER,
  SUPER_AGENT_SCHOOL,
};
